In [1]:
import numpy as np
from helpers import tridag
from helpers import create_laplacian

In [2]:
dzc_f = np.fromfile('scratch/fortran/dzc.bin')
dzf_f = np.fromfile('scratch/fortran/dzf.bin')

dzc_p = np.fromfile('scratch/python/dzc.bin')
dzf_p = np.fromfile('scratch/python/dzf.bin')


In [26]:
dzc_f

array([0.06219392, 0.06219392, 0.07857989, 0.09734117, 0.1176739 ,
       0.13812742, 0.15664328, 0.17084723, 0.17859319, 0.17859319,
       0.17084723, 0.15664328, 0.13812742, 0.1176739 , 0.09734117,
       0.07857989, 0.06219392, 0.06219392])

In [27]:
dzc_p

array([0.06219392, 0.06219392, 0.07857989, 0.09734117, 0.1176739 ,
       0.13812742, 0.15664328, 0.17084723, 0.17859319, 0.17859319,
       0.17084723, 0.15664328, 0.13812742, 0.1176739 , 0.09734117,
       0.07857989, 0.06219392, 0.06219392])

In [2]:
a_f = np.fromfile('scratch/fortran/a.bin')
bb_f = np.fromfile('scratch/fortran/bb.bin')
c_f = np.fromfile('scratch/fortran/c.bin')
r_f = np.fromfile('scratch/fortran/r.bin')
u_f = np.fromfile('scratch/fortran/u.bin')

a_p = np.fromfile('scratch/python/a.bin')
bb_p = np.fromfile('scratch/python/bb.bin')
c_p = np.fromfile('scratch/python/c.bin')
r_p = np.fromfile('scratch/python/r.bin')
u_p = np.fromfile('scratch/python/u.bin')

print(np.allclose(a_f, a_p))
print(np.allclose(bb_f, bb_p))
print(np.allclose(c_f, c_p))
print(np.allclose(r_f, r_p))
print(np.allclose(u_f, u_p))

True
True
True
True
True


In [24]:
r_p

array([-7.77156117e-16,  1.88737914e-15, -6.66133815e-16,  1.22124533e-15,
       -9.99200722e-16,  2.77555756e-16,  5.55111512e-17,  2.91433544e-16,
       -6.93889390e-17,  1.66533454e-16, -2.22044605e-16,  9.99200722e-16,
        3.55271368e-15,  8.88178420e-16, -1.88737914e-15,  7.77156117e-16])

In [33]:
r_f[4] - r_p[4]

4.3298697960381105e-15

In [34]:
np.linalg.norm(r_f - r_p)

4.3298697960381105e-15

In [30]:
test = r_f.copy()
#test[4] = -9.99200722e-16
tridag(a_f, bb_f, c_f, test, a_f.size)
print(test)

[0.23844214 0.23844214 0.23844214 0.23844214 0.23844214 0.23844214
 0.23844214 0.23844214 0.23844214 0.23844214 0.23844214 0.23844214
 0.23844214 0.23844214 0.23844214 0.23844214]


In [5]:
test = r_p.copy()
tridag(a_p, bb_p, c_p, test, a_p.size)
print(test)

[0.12595423 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423
 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423
 0.12595423 0.12595423 0.12595423 0.12595423]


In [17]:
a, b, c = create_laplacian(16, dzf_f, dzc_f)
test = r_p.copy()
tridag(a_p, bb_p, c_p, r_p, 16)
print(test)

[0.12595423 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423
 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423 0.12595423
 0.12595423 0.12595423 0.12595423 0.12595423]


In [19]:
r_p

array([4.73798685e+13, 4.73798685e+13, 4.73798685e+13, 4.73798685e+13,
       4.73798685e+13, 4.73798685e+13, 4.73798685e+13, 4.73798685e+13,
       4.73798685e+13, 4.73798685e+13, 4.73798685e+13, 4.73798685e+13,
       4.73798685e+13, 4.73798685e+13, 4.73798685e+13, 4.73798685e+13])

In [20]:
r_f

array([-7.77156117e-16,  1.88737914e-15, -6.66133815e-16,  1.22124533e-15,
        3.33066907e-15,  2.77555756e-16,  5.55111512e-17,  2.91433544e-16,
       -6.93889390e-17,  1.66533454e-16, -2.22044605e-16,  9.99200722e-16,
        3.55271368e-15,  8.88178420e-16, -1.88737914e-15,  7.77156117e-16])